\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}

<<chunk>>=
require(googlesheets, echo = FALSE)
setwd('~/Dropbox (2.0)/Work/Software/dwulff.github.io/')
options(stringsAsFactors = F)

goodchoices = read.table('_Goodchoices/GoodchoicesSurveys.txt',header=F,sep='\n')[,1]
networks    = read.table('_Networks/NetworksSurveys.txt',header=F,sep='\n')[,1]






list = c('a','b','c')
cat(list,sep='\n')
@


\end{document}